services:
  app:
    # REPLACE THIS WITH YOUR DOCKERHUB USERNAME
    image: nathanmendis/project-harvey:latest
    container_name: project-harvey

    command: daphne -b 0.0.0.0 -p 8000 project_harvey.asgi:application
    # No volume mount needed, code is inside the image
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=project_harvey
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,project-harvey

      - DJANGO_SETTINGS_MODULE=project_harvey.settings

    # Secrets are injected here at runtime!
    # Option 1: Users create a .env file locally
    env_file:
      - .env
    # Option 2: Users explicitly set keys here (less secure for sharing)
    # environment:
    #   - GROQ_API_KEY=your_key_here

    depends_on:
      - db
      - redis

  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_DB=project_harvey
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
